use serde::Serialize;

/// Compatibility profiles (PRD §34–35).
#[derive(Debug, Clone, Serialize)]
pub struct Recommendation {
    pub profile: &'static str,
    pub runtime_hint: &'static str,
    pub graphics: &'static str,
    pub windows_version: &'static str,
    pub dependencies: Vec<&'static str>,
    pub launch_arguments: Vec<String>,
    pub compatibility: u32,
    pub notes: Vec<&'static str>,
}

/// Comprehensive Game Catalog Item for the FusionCross Store & Library.
#[derive(Debug, Clone, Serialize)]
pub struct GameCatalogItem {
    pub id: &'static str,
    pub title: &'static str,
    pub developer: &'static str,
    pub category: &'static str, // "Stores & Launchers", "Action & RPG", "Indie & Classics", "Shooters & Online", "Creative & Utilities"
    pub tier: &'static str,     // "Platinum", "Gold", "Silver", "Blocked"
    pub compatibility: u32,
    pub graphics_backend: &'static str, // "d3dmetal", "dxvk", "wined3d"
    pub windows_version: &'static str,  // "win10", "win11", "win7"
    pub directx_version: &'static str,  // "DirectX 12", "DirectX 11", "DirectX 9", "Vulkan"
    pub msync_recommended: bool,
    pub dependencies: Vec<&'static str>,
    pub launch_arguments: Vec<&'static str>,
    pub installer_url: Option<&'static str>,
    pub notes: &'static str,
    pub anti_cheat_status: &'static str, // "Supported", "Singleplayer Only", "Kernel Driver Incompatible"
}

/// Full Curated Catalog of 50+ Top Windows Games & Launchers on macOS Apple Silicon.
pub fn get_catalog() -> Vec<GameCatalogItem> {
    vec![
        // ==========================================
        // 1. GAME STORES & LAUNCHERS
        // ==========================================
        GameCatalogItem {
            id: "steam",
            title: "Steam Client",
            developer: "Valve Corporation",
            category: "Stores & Launchers",
            tier: "Platinum",
            compatibility: 96,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["corefonts", "vcrun2022"],
            launch_arguments: vec![
                "-no-cef-sandbox",
                "-cef-disable-gpu",
                "-cef-disable-hang-monitor",
                "-allpackagedcontent",
                "-noverifyfiles",
                "-allosarches",
            ],
            installer_url: Some("https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe"),
            notes: "Flawless store navigation, cloud saves, and native controller support. Essential starting point.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "battlenet",
            title: "Battle.net Desktop App",
            developer: "Blizzard Entertainment",
            category: "Stores & Launchers",
            tier: "Gold",
            compatibility: 90,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 11 / 12",
            msync_recommended: true,
            dependencies: vec!["corefonts", "vcrun2022"],
            launch_arguments: vec![],
            installer_url: Some("https://www.battle.net/download/getInstallerForGame?os=win&gameProgram=BATTLENET_APP&version=Live"),
            notes: "Required for Diablo IV, World of Warcraft, and Overwatch 2. Stable with MSync.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "epicgames",
            title: "Epic Games Launcher",
            developer: "Epic Games",
            category: "Stores & Launchers",
            tier: "Gold",
            compatibility: 88,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["corefonts", "vcrun2022"],
            launch_arguments: vec![],
            installer_url: Some("https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi"),
            notes: "Disable in-game community overlay in client preferences to prevent micro-stutters.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "gog",
            title: "GOG GALAXY",
            developer: "CD Projekt",
            category: "Stores & Launchers",
            tier: "Platinum",
            compatibility: 94,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["corefonts", "vcrun2022"],
            launch_arguments: vec![],
            installer_url: Some("https://content-system.gog.com/open_link/download?path=/open/galaxy/client/2.0.73.27/setup_galaxy_2.0.73.27.exe"),
            notes: "DRM-free games launch directly with zero overlay interference.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "eaapp",
            title: "EA App",
            developer: "Electronic Arts",
            category: "Stores & Launchers",
            tier: "Silver",
            compatibility: 82,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["corefonts", "vcrun2022"],
            launch_arguments: vec![],
            installer_url: Some("https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe"),
            notes: "Required for EA Play titles. Keep background services enabled.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "heroic",
            title: "Heroic Games Launcher",
            developer: "Heroic Games",
            category: "Stores & Launchers",
            tier: "Platinum",
            compatibility: 98,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11 / 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Fast, privacy-friendly Epic & GOG manager with built-in Wine management.",
            anti_cheat_status: "Supported",
        },

        // ==========================================
        // 2. AAA ACTION & RPG HITS
        // ==========================================
        GameCatalogItem {
            id: "cyberpunk",
            title: "Cyberpunk 2077: Phantom Liberty",
            developer: "CD Projekt Red",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 88,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022", "d3dcompiler_47"],
            launch_arguments: vec!["-skipStartScreen"],
            installer_url: None,
            notes: "Apple GPTK D3DMetal delivers 60+ FPS on M-series chips with FSR 2.1 Quality enabled.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "eldenring",
            title: "Elden Ring: Shadow of the Erdtree",
            developer: "FromSoftware",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 87,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Runs smoothly with D3DMetal. Use offline toggle to bypass Easy Anti-Cheat on Wine.",
            anti_cheat_status: "Singleplayer Only",
        },
        GameCatalogItem {
            id: "baldursgate3",
            title: "Baldur's Gate 3",
            developer: "Larian Studios",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 93,
            graphics_backend: "d3dmetal",
            windows_version: "win11",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019", "corefonts"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Select DirectX 11 mode in Larian launcher for peak frame rates and rock-solid stability.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "gtav",
            title: "Grand Theft Auto V",
            developer: "Rockstar Games",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 91,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019", "d3dcompiler_47"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Story mode delivers high framerates with DXVK and MSync.",
            anti_cheat_status: "Singleplayer Only",
        },
        GameCatalogItem {
            id: "witcher3",
            title: "The Witcher 3: Wild Hunt (Next-Gen)",
            developer: "CD Projekt Red",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 92,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 11 / 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Next-gen graphics supported. DirectX 11 mode offers the highest FPS on base M1/M2/M3 chips.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "rdr2",
            title: "Red Dead Redemption 2",
            developer: "Rockstar Games",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 84,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12 / Vulkan",
            msync_recommended: true,
            dependencies: vec!["vcrun2022", "d3dcompiler_47"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Requires D3DMetal (Apple GPTK). High texture quality with FSR Quality is optimal.",
            anti_cheat_status: "Singleplayer Only",
        },
        GameCatalogItem {
            id: "hogwarts",
            title: "Hogwarts Legacy",
            developer: "Avalanche Software",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 83,
            graphics_backend: "d3dmetal",
            windows_version: "win11",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Enable FSR 2.0 Balanced for smooth 60 FPS exploration across Hogwarts Castle.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "armoredcore6",
            title: "Armored Core VI: Fires of Rubicon",
            developer: "FromSoftware",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 93,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "FromSoftware's smoothest 60 FPS mech title on Apple Silicon Wine.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "sekiro",
            title: "Sekiro: Shadows Die Twice",
            developer: "FromSoftware",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 95,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Locked 60 FPS with full DualSense & Xbox controller vibration.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "darksouls3",
            title: "Dark Souls III",
            developer: "FromSoftware",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 94,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Flawless performance with DXVK shader compilation caching.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "liesofp",
            title: "Lies of P",
            developer: "Round8 Studio",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 94,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Unreal Engine 4 runs at 60-90 FPS with D3DMetal and MetalFX/FSR.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "ghostoftsushima",
            title: "Ghost of Tsushima Director's Cut",
            developer: "Sucker Punch / Nixxes",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 86,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "PlayStation PC port runs at high fidelity on D3DMetal with MSync.",
            anti_cheat_status: "Singleplayer Only",
        },
        GameCatalogItem {
            id: "godofwar",
            title: "God of War (2018)",
            developer: "Santa Monica Studio",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 88,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Solid 50-60 FPS on M2/M3/M4 with FSR 2.0 set to Quality.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "spiderman",
            title: "Marvel's Spider-Man Remastered",
            developer: "Insomniac Games / Nixxes",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 85,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Disable Ray Tracing in graphics options for fluid 60 FPS web-slinging.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "horizonzerodawn",
            title: "Horizon Zero Dawn Complete Edition",
            developer: "Guerrilla Games",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 85,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Initial shader compilation takes ~3 minutes; subsequent gameplay is smooth.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "palworld",
            title: "Palworld",
            developer: "Pocketpair",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 87,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Unreal Engine 5 title; runs smoothly with FSR / TSR upscaling enabled.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "monsterhunterworld",
            title: "Monster Hunter: World",
            developer: "Capcom",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 89,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Enable DirectX 11 and DXVK Async for fluid multiplayer hunts.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "re4remake",
            title: "Resident Evil 4 (Remake)",
            developer: "Capcom",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 84,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Capcom's RE Engine runs with high efficiency under D3DMetal.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "raji",
            title: "Raji: An Ancient Epic",
            developer: "Nodding Heads Games",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 95,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 11 / 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2019", "d3dcompiler_47"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Acclaimed mythic action-adventure runs with stunning visual fidelity and controller support.",
            anti_cheat_status: "Supported",
        },

        // ==========================================
        // 3. JRPG & STRATEGY & CLASSIC RPGS
        // ==========================================
        GameCatalogItem {
            id: "persona5royal",
            title: "Persona 5 Royal",
            developer: "ATLUS",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 96,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Locked 60/120 FPS; flawless anime visuals and controller response.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "persona3reload",
            title: "Persona 3 Reload",
            developer: "ATLUS",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 89,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Turn off screen-space reflections if experiencing minor frame dips in Tartarus.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "ff7remake",
            title: "Final Fantasy VII Remake Intergrade",
            developer: "Square Enix",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 87,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Unreal Engine 4 title; dynamic resolution scaler keeps frames solid at 60.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "skyrim",
            title: "The Elder Scrolls V: Skyrim Special Edition",
            developer: "Bethesda Game Studios",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 98,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Flawless out of the box. Fully supports Mod Organizer 2 and SKSE64.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "fallout4",
            title: "Fallout 4: Game of the Year Edition",
            developer: "Bethesda Game Studios",
            category: "Action & RPG",
            tier: "Platinum",
            compatibility: 93,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "High FPS Physics Fix mod recommended for 60+ Hz ProMotion displays.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "diablo4",
            title: "Diablo IV",
            developer: "Blizzard Entertainment",
            category: "Action & RPG",
            tier: "Gold",
            compatibility: 82,
            graphics_backend: "d3dmetal",
            windows_version: "win11",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Requires Battle.net and D3DMetal (Apple GPTK). Solid 60 FPS on High settings.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "rimworld",
            title: "RimWorld",
            developer: "Ludeon Studios",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Near native execution; thousands of Steam Workshop mods supported.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "factorio",
            title: "Factorio",
            developer: "Wube Software",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "60 UPS / 60 FPS even on massive megabases.",
            anti_cheat_status: "Supported",
        },

        // ==========================================
        // 4. INDIE LEGENDS & CASUAL
        // ==========================================
        GameCatalogItem {
            id: "hades",
            title: "Hades",
            developer: "Supergiant Games",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Gold standard of Wine compatibility; 120 FPS ProMotion with full DualSense.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "hades2",
            title: "Hades II",
            developer: "Supergiant Games",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 98,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Early access runs flawlessly with native controller support.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "hollowknight",
            title: "Hollow Knight",
            developer: "Team Cherry",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Responsive 60/120 FPS; zero input delay.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "slaythespire",
            title: "Slay the Spire",
            developer: "Mega Crit Games",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "wined3d",
            windows_version: "win10",
            directx_version: "DirectX 9 / 11",
            msync_recommended: false,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Flawless card battler; instant loads and full touch / trackpad support.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "stardewvalley",
            title: "Stardew Valley",
            developer: "ConcernedApe",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["corefonts"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "100% playable; SMAPI modding works seamlessly.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "celeste",
            title: "Celeste",
            developer: "Maddy Makes Games",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Precision platforming with sub-millisecond input lag.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "davethediver",
            title: "Dave the Diver",
            developer: "MINTROCKET",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 97,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Silky smooth underwater exploration and sushi bar management.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "cuphead",
            title: "Cuphead",
            developer: "Studio MDHR",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Authentic 1930s animation runs locked at native display refresh rate.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "subnautica",
            title: "Subnautica",
            developer: "Unknown Worlds",
            category: "Indie & Classics",
            tier: "Gold",
            compatibility: 91,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Underwater survival runs well with DXVK shader pipeline.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "terraria",
            title: "Terraria",
            developer: "Re-Logic",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 98,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["corefonts"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Supports tModLoader and multiplayer.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "deeprock",
            title: "Deep Rock Galactic",
            developer: "Ghost Ship Games",
            category: "Shooters & Online",
            tier: "Platinum",
            compatibility: 92,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec!["-dx11"],
            installer_url: None,
            notes: "Use -dx11 launch flag in Steam for best FPS.",
            anti_cheat_status: "Supported",
        },

        // ==========================================
        // 5. SHOOTERS, MMOS & CLASSIC VALVE
        // ==========================================
        GameCatalogItem {
            id: "warframe",
            title: "Warframe",
            developer: "Digital Extremes",
            category: "Shooters & Online",
            tier: "Gold",
            compatibility: 91,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Runs smoothly; enable DX11 in launcher settings.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "wow",
            title: "World of Warcraft",
            developer: "Blizzard Entertainment",
            category: "Shooters & Online",
            tier: "Platinum",
            compatibility: 94,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 11 / 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Select DirectX 11 in system settings for best consistency.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "overwatch2",
            title: "Overwatch 2",
            developer: "Blizzard Entertainment",
            category: "Shooters & Online",
            tier: "Gold",
            compatibility: 88,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Requires Battle.net. DXVK compile stutter disappears after initial map warm-up.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "rocketleague",
            title: "Rocket League",
            developer: "Psyonix",
            category: "Shooters & Online",
            tier: "Platinum",
            compatibility: 95,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Ultra responsive 120/144 FPS with gamepads.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "cs2",
            title: "Counter-Strike 2",
            developer: "Valve Corporation",
            category: "Shooters & Online",
            tier: "Silver",
            compatibility: 80,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "Vulkan / DX11",
            msync_recommended: true,
            dependencies: vec!["corefonts", "vcrun2022"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Runs via Steam. Singleplayer and community servers work; Valve Anti-Cheat is active.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "doometernal",
            title: "DOOM Eternal",
            developer: "id Software",
            category: "Shooters & Online",
            tier: "Platinum",
            compatibility: 96,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "Vulkan",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Vulkan id Tech 7 runs at blisteringly high frame rates on Apple Silicon.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "portal2",
            title: "Portal & Portal 2",
            developer: "Valve Corporation",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 9 / 11",
            msync_recommended: true,
            dependencies: vec!["corefonts"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Source engine perfection on macOS Wine.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "halflife2",
            title: "Half-Life 2",
            developer: "Valve Corporation",
            category: "Indie & Classics",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 9",
            msync_recommended: true,
            dependencies: vec!["corefonts"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Flawless classic PC gaming experience with full mod compatibility.",
            anti_cheat_status: "Supported",
        },

        // ==========================================
        // 6. ANTI-CHEAT TRANSPARENCY (CLEAR USER GUIDANCE)
        // ==========================================
        GameCatalogItem {
            id: "valorant",
            title: "Valorant",
            developer: "Riot Games",
            category: "Shooters & Online",
            tier: "Blocked",
            compatibility: 5,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "BLOCKED: Riot Vanguard uses a ring-0 Windows kernel driver that cannot run in macOS user space.",
            anti_cheat_status: "Kernel Driver Incompatible",
        },
        GameCatalogItem {
            id: "fortnite",
            title: "Fortnite",
            developer: "Epic Games",
            category: "Shooters & Online",
            tier: "Blocked",
            compatibility: 5,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "BLOCKED: Easy Anti-Cheat / BattlEye kernel drivers are not supported by Wine on macOS.",
            anti_cheat_status: "Kernel Driver Incompatible",
        },
        GameCatalogItem {
            id: "destiny2",
            title: "Destiny 2",
            developer: "Bungie",
            category: "Shooters & Online",
            tier: "Blocked",
            compatibility: 5,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "BLOCKED: Bungie BattlEye kernel driver will reject or ban Wine launch attempts.",
            anti_cheat_status: "Kernel Driver Incompatible",
        },
        GameCatalogItem {
            id: "leagueoflegends",
            title: "League of Legends",
            developer: "Riot Games",
            category: "Action & RPG",
            tier: "Blocked",
            compatibility: 10,
            graphics_backend: "wined3d",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: false,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "BLOCKED: Vanguard anti-cheat update now blocks the Windows client on Wine. (Play official macOS client instead).",
            anti_cheat_status: "Kernel Driver Incompatible",
        },

        // ==========================================
        // 7. PRODUCTIVITY & CREATIVE UTILITIES
        // ==========================================
        GameCatalogItem {
            id: "photoshop",
            title: "Adobe Photoshop 2024",
            developer: "Adobe Systems",
            category: "Creative & Utilities",
            tier: "Gold",
            compatibility: 88,
            graphics_backend: "d3dmetal",
            windows_version: "win10",
            directx_version: "DirectX 12",
            msync_recommended: true,
            dependencies: vec!["vcrun2022", "corefonts"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "GPU acceleration is active. Camera RAW and standard filters work smoothly.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "autocad",
            title: "Autodesk AutoCAD",
            developer: "Autodesk",
            category: "Creative & Utilities",
            tier: "Silver",
            compatibility: 72,
            graphics_backend: "dxvk",
            windows_version: "win10",
            directx_version: "DirectX 11",
            msync_recommended: true,
            dependencies: vec!["vcrun2019"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "3D viewport rendering relies on WineD3D/DXVK. 2D drafting is responsive.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "notepadpp",
            title: "Notepad++",
            developer: "Don Ho",
            category: "Creative & Utilities",
            tier: "Platinum",
            compatibility: 99,
            graphics_backend: "wined3d",
            windows_version: "win7",
            directx_version: "GDI",
            msync_recommended: false,
            dependencies: vec![],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Lightweight text editor runs instantaneously with zero overhead.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "office",
            title: "Microsoft Office 2021",
            developer: "Microsoft Corporation",
            category: "Creative & Utilities",
            tier: "Gold",
            compatibility: 84,
            graphics_backend: "wined3d",
            windows_version: "win10",
            directx_version: "GDI / DirectWrite",
            msync_recommended: false,
            dependencies: vec!["corefonts", "msxml6"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Core Word, Excel, and PowerPoint editing work reliably with CoreFonts installed.",
            anti_cheat_status: "Supported",
        },
        GameCatalogItem {
            id: "gimp",
            title: "GIMP Windows Build",
            developer: "The GIMP Team",
            category: "Creative & Utilities",
            tier: "Platinum",
            compatibility: 90,
            graphics_backend: "wined3d",
            windows_version: "win10",
            directx_version: "Direct2D",
            msync_recommended: false,
            dependencies: vec!["corefonts"],
            launch_arguments: vec![],
            installer_url: None,
            notes: "Open source image manipulation suite with full plugin support.",
            anti_cheat_status: "Supported",
        },
    ]
}

/// Best-matching profile for an app name (also drives the installer wizard).
pub fn recommend(app_name: &str) -> Recommendation {
    let lower = app_name.to_lowercase();
    let mut catalog = get_catalog();
    // Sort by title length descending so longer/more specific titles (e.g. "Hades II") match before substrings (e.g. "Hades")
    catalog.sort_by_key(|b| std::cmp::Reverse(b.title.len()));

    // 1. Check if name matches any game catalog item
    for item in &catalog {
        let title_lower = item.title.to_lowercase();
        let id_lower = item.id.to_lowercase();
        if lower.contains(&title_lower) || lower.contains(&id_lower) {
            return Recommendation {
                profile: item.id,
                runtime_hint: if item.graphics_backend == "d3dmetal" {
                    "Wine-GE"
                } else {
                    "Wine Stable"
                },
                graphics: item.graphics_backend,
                windows_version: item.windows_version,
                dependencies: item.dependencies.clone(),
                launch_arguments: item
                    .launch_arguments
                    .iter()
                    .map(|s| s.to_string())
                    .collect(),
                compatibility: item.compatibility,
                notes: vec![item.notes],
            };
        }
    }

    // 2. Fallback key matching
    if lower.contains("steam") {
        return Recommendation {
            profile: "steam",
            runtime_hint: "Wine Stable",
            graphics: "dxvk",
            windows_version: "win10",
            dependencies: vec!["corefonts", "vcrun2022"],
            launch_arguments: vec![
                "-no-cef-sandbox".into(),
                "-cef-disable-gpu".into(),
                "-cef-disable-hang-monitor".into(),
            ],
            compatibility: 96,
            notes: vec!["Steam client profile applied."],
        };
    }

    if lower.contains("photoshop") {
        return Recommendation {
            profile: "photoshop",
            runtime_hint: "Wine-GE",
            graphics: "d3dmetal",
            windows_version: "win10",
            dependencies: vec!["vcrun2022", "corefonts"],
            launch_arguments: vec![],
            compatibility: 88,
            notes: vec!["Adobe Photoshop profile applied."],
        };
    }

    // 3. Default recommendation
    Recommendation {
        profile: "default",
        runtime_hint: "Wine Stable",
        graphics: "automatic",
        windows_version: "win10",
        dependencies: vec!["corefonts"],
        launch_arguments: vec![],
        compatibility: 80,
        notes: vec!["No specific profile found; general defaults applied."],
    }
}

/// Adjust a recommendation's score based on what is actually available.
#[allow(dead_code, unused)]
pub fn adjusted_score(base: u32, runtime_available: bool, graphics: &str) -> u32 {
    let mut score = base;
    if !runtime_available {
        score = score.saturating_sub(20);
    }
    if graphics == "d3dmetal" {
        score = score.saturating_sub(5);
    }
    score.min(99)
}

/// Persistable compatibility record for a registered application.
#[allow(dead_code, unused)]
pub fn profile_for_app(app_id: &str, rec: &Recommendation) -> serde_json::Value {
    serde_json::json!({
        "app_id": app_id,
        "profile": rec.profile,
        "runtime": rec.runtime_hint,
        "graphics": rec.graphics,
        "windows_version": rec.windows_version,
        "compatibility": rec.compatibility,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recommends_known_and_default() {
        let photoshop = recommend("Adobe Photoshop 2024");
        assert_eq!(photoshop.profile, "photoshop");
        assert_eq!(photoshop.graphics, "d3dmetal");

        let steam = recommend("Steam Installer");
        assert_eq!(steam.profile, "steam");

        let anything = recommend("RandomTool Foo");
        assert_eq!(anything.profile, "default");
        assert_eq!(anything.compatibility, 80);
    }

    #[test]
    fn recommends_top_games() {
        let cp = recommend("Cyberpunk 2077");
        assert_eq!(cp.profile, "cyberpunk");
        assert_eq!(cp.graphics, "d3dmetal");

        let hades = recommend("Hades II");
        assert_eq!(hades.profile, "hades2");

        let raji = recommend("Raji: An Ancient Epic");
        assert_eq!(raji.profile, "raji");
    }

    #[test]
    fn catalog_has_comprehensive_games() {
        let cat = get_catalog();
        assert!(cat.len() >= 40);
        let steam = cat.iter().find(|i| i.id == "steam").expect("steam exists");
        assert_eq!(steam.tier, "Platinum");
        assert!(steam.installer_url.is_some());
    }

    #[test]
    fn missing_runtime_penalizes() {
        assert_eq!(adjusted_score(90, false, "wined3d"), 70);
        assert_eq!(adjusted_score(90, true, "dxvk"), 90);
    }
}
